
version: '3.8'

services:
# Database Service (Mysql)
  datasource:
    image: mysql
    container_name: datasource
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studentdb
      - MYSQL_USER=mysqldb
      - MYSQL_PASSWORD=ongdinh101199
    #ports:
      #- 3306:3306
    networks:
      - angular_course_backend
    volumes:
      - mysqldata:/var/lib/mysql
      
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    container_name: springboot-server
    build:
      context: ./api-student-management
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - datasource # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://datasource:3306/studentdb
      SPRING_DATASOURCE_USERNAME: mysqldb
      SPRING_DATASOURCE_PASSWORD: ongdinh101199
      
     
    networks:
      - angular_course_backend
      - angular_course_frontend

  # Frontend Service 
  app-client:
    container_name: angular-client
    build:
      context: ./angular-qlsv-demo
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - angular_course_backend
      
networks:
  angular_course_backend:
  angular_course_frontend:
volumes:
  mysqldata:
 